"""autogenerated at startup.

Revision ID: b7a9b0653d5f
Revises: 
Create Date: 2025-11-02 18:54:48.418249
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7a9b0653d5f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth2_token',
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('token_json', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('created_by', 'name', name='uq_oauth2_token_creator_name')
    )
    op.create_index(op.f('ix_oauth2_token_created_by'), 'oauth2_token', ['created_by'], unique=False)
    op.create_index('ix_oauth2_token_created_by_name', 'oauth2_token', ['created_by', 'name'], unique=False)
    op.create_index('ix_oauth2_token_expires_at', 'oauth2_token', ['expires_at'], unique=False)
    op.create_index(op.f('ix_oauth2_token_id'), 'oauth2_token', ['id'], unique=False)
    op.create_index(op.f('ix_oauth2_token_name'), 'oauth2_token', ['name'], unique=False)
    op.create_index(op.f('ix_oauth2_token_provider'), 'oauth2_token', ['provider'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oauth2_token_provider'), table_name='oauth2_token')
    op.drop_index(op.f('ix_oauth2_token_name'), table_name='oauth2_token')
    op.drop_index(op.f('ix_oauth2_token_id'), table_name='oauth2_token')
    op.drop_index('ix_oauth2_token_expires_at', table_name='oauth2_token')
    op.drop_index('ix_oauth2_token_created_by_name', table_name='oauth2_token')
    op.drop_index(op.f('ix_oauth2_token_created_by'), table_name='oauth2_token')
    op.drop_table('oauth2_token')
    # ### end Alembic commands ###
