"""autogenerated at startup.

Revision ID: cfbf74ffc96c
Revises:
Create Date: 2025-10-05 14:32:05.421274
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cfbf74ffc96c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade the revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "heartbeat",
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "last_seen", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_heartbeat_id"), "heartbeat", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_heartbeat_id"), table_name="heartbeat")
    op.drop_table("heartbeat")
    # ### end Alembic commands ###
