"""autogenerated at startup.

Revision ID: d63e36276587
Revises: 
Create Date: 2025-11-02 19:14:53.731109
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd63e36276587'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('id_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_in', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('token_type', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('created_by', 'tenant_id', name='uq_oauth2_token_creator_conn')
    )
    op.create_index('ix_oauth2_token_creator_conn', 'token', ['created_by', 'tenant_id'], unique=False)
    op.create_index(op.f('ix_token_created_by'), 'token', ['created_by'], unique=False)
    op.create_index(op.f('ix_token_id'), 'token', ['id'], unique=False)
    op.create_index(op.f('ix_token_name'), 'token', ['name'], unique=False)
    op.create_index(op.f('ix_token_tenant_id'), 'token', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_tenant_id'), table_name='token')
    op.drop_index(op.f('ix_token_name'), table_name='token')
    op.drop_index(op.f('ix_token_id'), table_name='token')
    op.drop_index(op.f('ix_token_created_by'), table_name='token')
    op.drop_index('ix_oauth2_token_creator_conn', table_name='token')
    op.drop_table('token')
    # ### end Alembic commands ###
